### ISSUE TITLE
Push latest version to crates.io

### ISSUE THREAD

**Issue by Huskehhh** [a1ien/rusb#121]
Hi,
I'm in need of this commit containing libusb [1.0.25](https://github.com/a1ien/rusb/commit/b9662aaeb9c3aef453b6cd39e32d5a0115f04080)

Are you able to push the latest version to crates.io?

Thanks 👍

**Comment by a1ien** [comment]
Because in 1.0.25 too mach regression I have plan wait 1.0.26 release https://github.com/libusb/libusb/issues/1047

**Comment by Huskehhh** [comment]
Thanks for the reply. 
I look forward to the new version. 👍

**Comment by Huskehhh** [comment]
Hi, Just a heads up, looks like 1.0.26 has been released recently.

**Comment by a1ien** [comment]
Yes. I going to release today.

**Comment by Huskehhh** [comment]
Thanks heaps!
