### ISSUE TITLE
Is it possible to use rusb after a fork()?

### ISSUE THREAD

**Issue by createyourpersonalaccount** [a1ien/rusb#122]
Hello,

I am trying to use [rusb](https://crates.io/crates/rusb) together with [daemonize](https://crates.io/crates/daemonize), which forks the process. I have noticed that the crate doesn't work as intended when I do so. 

If you could provide some help for me to understand how to do this properly it would be very much appreciated. I think this has something to do with `GlobalContext` but I don't understand how to use it across forks.

[libusb warns about `fork()`](https://libusb.sourceforge.io/api-1.0/libusb_caveats.html) but what I want is to delay the initialization of the context until the process is daemonized, which is different, i.e. I don't wish to have libusb or rusb work between parent and child process which is what libusb warns of I believe.

**Comment by a1ien** [comment]
What you mean by "doesn't work as intended"
I can suggest it is use [Context](https://docs.rs/rusb/latest/rusb/struct.Context.html) instead `GlobalContext`. And create `Context` after fork

**Comment by createyourpersonalaccount** [comment]
@a1ien 

My apologies, it works fine.

I was tired and after daemonizing I could not detect certain peripherals... but that's because I had removed them from their buses! So the "bug" was that I forgot that I removed the USBs and then I couldn't detect them...
