### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by dvc94ch** [a1ien/rusb#131]
read_bulk, write_bulk doesn't say anything about buffer size. it seems like the maximum that can be received in one read_bulk is 0xffff.

another gotcha seems to be when using `set_active_configuration` with the already active configuration a `-E_SHUTDOWN` is returned. docs should probably mention not to do that.

**Comment by a1ien** [comment]
> read_bulk, write_bulk doesn't say anything about buffer size. it seems like the maximum that can be received in one read_bulk is 0xffff.
It is not true.

> another gotcha seems to be when using set_active_configuration with the already active configuration a -E_SHUTDOWN is returned. docs should probably mention not to do that.

This is no error E_SHUTDOWN.

**Comment by dvc94ch** [comment]
linux. according to [0] it is indeed an error code (not a libusb one). sorry meant 16384, converted it to hex wrong :facepalm: apparently that's some kind of limitation due to usbfs (found a comment in some usb code).

- [0] https://www.kernel.org/doc/html/latest/driver-api/usb/error-codes.html

**Comment by a1ien** [comment]
> sorry meant 16384, converted it to hex wrong 🤦 apparently that's some kind of limitation due to usbfs (found a comment in some usb code).

In linux I can read large then 16384 and 65535 bytes. I can read about 4MB with one read_bulk call.

I think about errors better use libusb documentation.
https://libusb.sourceforge.io/api-1.0/group__libusb__dev.html#ga785ddea63a2b9bcb879a614ca4867bed
And also according libusb documentation not limitation about size https://libusb.sourceforge.io/api-1.0/group__libusb__syncio.html#ga2f90957ccc1285475ae96ad2ceb1f58c

**Comment by dvc94ch** [comment]
> In linux I can read large then 16384 and 65535 bytes. I can read about 4MB with one read_bulk call.

that is interesting. so actually over the wire it's packets of 512 bytes grouped in a transfer. so it will return up to 4MB of data from a transfer? wondering why I've seen code artificially limit the data per transfer to 16384 bytes.

the libusb error I got was LIBUSB_ERROR_NO_DEVICE when setting the active configuration to the existing active configuration when interfacing an android device via usb. now I just skip the `set_active_config` when it's already activated.

**Comment by a1ien** [comment]
For example. You can look at this commit(this from usb PTP library) https://github.com/a1ien/libptp/commit/28d31ae2bdffd9e2471bdd90223c255787b136d7
Before this change, I could sometimes read giant buffers of 12 megabytes or more. But sometimes the reads failed and if start using chunk with 1MB and  after that I have no problem.

**Comment by dvc94ch** [comment]
it does seem to have some significance. in the libusb code it's called the MAX_BULK_BUFFER_LENGTH [0]

- [0] https://github.com/libusb/libusb/blob/master/libusb/os/linux_usbfs.h#L73

**Comment by a1ien** [comment]
I think more relevant https://github.com/libusb/libusb/blob/74059154ee1541e18f42e6815ece97be0df2c661/libusb/os/linux_usbfs.c#L1901

**Comment by dvc94ch** [comment]
anyway, overall it was quite neat working with rusb, so thank you. still don't quite understand the NO_DEVICE error after changing the active configuration [0] to the already active one, but it works well enough now.

- [0] https://github.com/cloudpeers/xbuild/blob/adb/mdb/src/usb.rs#L134
