### ISSUE TITLE
use Result<..> as return type of `open_device_with_vid_pid`

### ISSUE THREAD

**Issue by J-ZhengLi** [a1ien/rusb#139]
Currently this function returns an option which is impossible to know why it might fails to get a device handle.

I had to spent a few minutes checking everything to make sure they were correct, until I finally decided to loop thought the device list and open the desired one, and it turns out it was "Access denied"...

So, I'm guessing returning a result could be more helpful in this case.

**Comment by a1ien** [comment]
It's not possible to return error. Since this function use libusb_open_device_with_vid_pid from libusb and this function only return NULL ptr if error. Also it not recommended to use this function in real code.
