### ISSUE TITLE
Creating a device from path?

### ISSUE THREAD

**Issue by AZProductions** [a1ien/rusb#150]
Hello, I'm wondering if you can create a device from a path (`D:/` for example), without needing to use a for loop? Thanks for helping out!

**Comment by a1ien** [comment]
You can use `open_device_with_fd`

**Comment by AZProductions** [comment]
Thanks, but it is sadly only unix, which I'm not currently targeting. Thanks for helping out!

**Comment by a1ien** [comment]
On other platform it's impossible.

**Comment by AZProductions** [comment]
Great! Could you perhaps show an example, since I'm very new to rust 🤷‍♂️

**Comment by a1ien** [comment]
Example for what?

**Comment by AZProductions** [comment]
Creating a Device struct from a mount-point (e.g D:/)

**Comment by a1ien** [comment]
It's impossible. All example available here https://github.com/a1ien/rusb/tree/master/examples

**Comment by AZProductions** [comment]
Ok then, as far as I know, I'll then need to cycle through all devices to find one matching the desired mountpoint

**Comment by a1ien** [comment]
Why are you talking about mountpoint? How usb related to mount point. Here example how to open exact device my vid&pid https://github.com/a1ien/rusb/blob/master/examples/read_device.rs Also i suggest firstly read libusb documentation https://libusb.sourceforge.io/api-1.0/index.html

**Comment by AZProductions** [comment]
My main question was if there is a way to get the vid&pid from a mountpoint (optionally in a rusb Device)

**Comment by a1ien** [comment]
No. It's not possible with libusb/rusb
