### ISSUE TITLE
Receiving notifications despite a filter

### ISSUE THREAD

**Issue by joelreymont** [a1ien/rusb#157]
I set up a vid/pid filter expecting `ctx.handle_events` not to return unless a notification for my device of choice is received.

I receive `connect/disconnect` notifications for any device that's attached or detached, though.

Is there a bug in the code or am I supposed to manually figure out if my device was attached or detached, like I'm doing below?

In other words, how do I wait for my device to appear or disappear without polling for it?

```
   if rusb::has_hotplug() {
        let ctx = Context::new()?;

        let mut reg = Some(
            HotplugBuilder::new()
                .enumerate(true)
                .vendor_id(args.vid)
                .product_id(args.pid)
                .register(&ctx, Box::new(HotPlugHandler {}))?,
        );

        loop {
            ctx.handle_events(None).unwrap();
            if is_connected(ctx.devices(), args.vid, args.pid) {
                if let Some(reg) = reg.take() {
                    ctx.unregister_callback(reg);
                    break;
                }
            }
        }
 ```

**Comment by a1ien** [comment]
I can't reproduce you problem. What linux distro do you use?

**Comment by joelreymont** [comment]
I tested this on MacOS Venture (13.0.1) as well as Ubuntu 22.10. 

Please change the code in the loop to look like this and you may see what I'm complaining about:

```
               context.handle_events(None).unwrap();
                if let Some(reg) = reg.take() {
                    ctx.unregister_callback(reg);
                    break;
                }
```

You should see `context.handle_events` returning for _any_ device inserted or removed, not just the ones you are filtering for. If that's correct behavior then how do I wait for my device events without polling?

There are operations that should not be performed in the callbacks and it would be natural to wait for a device in the loop and then perform any necessary operations once the device was attached or detached.

**Comment by a1ien** [comment]
This is expected behavioral.  `handle_events` just handle any events. You should run it in separate thread.
If you wand get you device look at this example https://github.com/a1ien/rusb/issues/100#issuecomment-1012014210
