### ISSUE TITLE
Faild to open device on Windows 7 x64

### ISSUE THREAD

**Issue by LumaRay** [a1ien/rusb#158]
Hello.

I use example from https://github.com/a1ien/rusb/blob/master/examples/read_device.rs

rustc 1.66.0 (69f9c33d7 2022-12-12)
cargo 1.66.0 (d65d197ad 2022-11-15)
[dependencies]
rusb = "0.9"

> thread 'main' panicked at 'Device found but failed to open: Operation not supported or unimplemented on this platform', src\main.rs:64:27
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Running with backtrace:

> thread 'main' panicked at 'Device found but failed to open: Operation not supported or unimplemented on this platform', src\main.rs:64:27
> stack backtrace:
>    0: std::panicking::begin_panic_handler
>              at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\panicking.rs:575
>    1: core::panicking::panic_fmt
>              at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\core\src\panicking.rs:65
>    2: uem_reader::open_device<rusb::context::Context>
>              at .\src\main.rs:64
>    3: uem_reader::main
>              at .\src\main.rs:35
>    4: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
>              at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\core\src\ops\function.rs:251
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Full backtrace:

> thread 'main' panicked at 'Device found but failed to open: Operation not supported or unimplemented on this platform', src\main.rs:64:27
> stack backtrace:
>    0:        0x13f83b052 - std::sys_common::backtrace::_print::impl$0::fmt
>                                at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\sys_common\backtrace.rs:44
>    1:        0x13f84ad4b - core::fmt::write
>                                at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\core\src\fmt\mod.rs:1209
>    2:        0x13f8390ea - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
>                                at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\io\mod.rs:1682
>    3:        0x13f83ad9b - std::sys_common::backtrace::print
>                                at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\sys_common\backtrace.rs:35
>    4:        0x13f83d589 - std::panicking::default_hook::closure$1
>                                at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\panicking.rs:267
>    5:        0x13f83d20a - std::panicking::default_hook
>                                at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\panicking.rs:288
>    6:        0x13f83de11 - std::panicking::rust_panic_with_hook
>                                at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\panicking.rs:688
>    7:        0x13f83db9d - std::panicking::begin_panic_handler::closure$0
>                                at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\panicking.rs:579
>    8:        0x13f83ba7f - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
>                                at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\sys_common\backtrace.rs:137
>    9:        0x13f83d860 - std::panicking::begin_panic_handler
>                                at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\panicking.rs:575
>   10:        0x13f870ef5 - core::panicking::panic_fmt
>                                at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\core\src\panicking.rs:65
>   11:        0x13f828712 - uem_reader::open_device<rusb::context::Context>
>                                at D:\GitHub\uem-reader-rs\src\main.rs:64
>   12:        0x13f826008 - uem_reader::main
>                                at D:\GitHub\uem-reader-rs\src\main.rs:35
>   13:        0x13f82b35b - core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
>                                at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\core\src\ops\function.rs:251
>   14:        0x13f82d02e - std::sys_common::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<> >
>                                at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\std\src\sys_common\backtrace.rs:124
>   15:        0x13f824941 - std::rt::lang_start::closure$0<tuple$<> >
>                                at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\std\src\rt.rs:166
>   16:        0x13f8357be - std::rt::lang_start_internal
>                                at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\rt.rs:148
>   17:        0x13f82491a - std::rt::lang_start<tuple$<> >
>                                at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\std\src\rt.rs:165
>   18:        0x13f8264d9 - main
>   19:        0x13f86f55c - __scrt_common_main_seh
>                                at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
>   20:         0x778b556d - BaseThreadInitThunk
>   21:         0x77b1372d - RtlUserThreadStart

**Comment by a1ien** [comment]
You can read info how to use libusb under windows on libusb project wiki. 
https://github.com/libusb/libusb/wiki/Windows#how-to-use-libusb-on-windows
