### ISSUE TITLE
How to detect device type?

### ISSUE THREAD

**Issue by umneeq2** [a1ien/rusb#166]
Hello. How can I detect device type? Documentation primer outputs something like that:

Bus 004 Device 001: ID 1d6b:0003
Bus 003 Device 003: ID 046d:c31c
Bus 003 Device 002: ID 09da:f891
Bus 003 Device 001: ID 1d6b:0002
Bus 002 Device 001: ID 1d6b:0003
Bus 001 Device 003: ID 0525:a4ac
Bus 001 Device 002: ID 046d:0825
Bus 001 Device 001: ID 1d6b:0002
Among these devices I have qrcode scanner.
First question: How I can detect which one of them?
Second: How can I bind this scanner to my console program only? Now the scanner, when scanning a barcode, outputs a value to the program that has the input focus.
Thanx!

**Comment by a1ien** [comment]
You don't need rusb for this task. Usually the barcode scanner is presented as a keyboard. If you want to use the barcode scanner only in your application, you will have to write a hid device driver. I highly recommend you first read something about usb and how it work.

**Comment by umneeq2** [comment]
@a1ien, thank you!
