### ISSUE TITLE
rusb cannot open USB devices on Windows 11.

### ISSUE THREAD

**Issue by lethargy123** [a1ien/rusb#168]
I have been using rusb in my project, but after testing, I found that it is not working on the Windows platform. However, it works on Ubuntu. So, I tried running read_device.rs from the examples to test if there is an issue with my code. When I run it, the following error message is outputted:
thread 'main' panicked at 'Device found but failed to open: Operation not supported or unimplemented on this platform', src\main.rs:64:27
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
error: process didn't exit successfully: target\debug\test_v1.exe 6353 53261 (exit code: 101)

**Comment by Linken-code** [comment]
So am I, using rusb::has_hotplug method will return false,This makes it unusable in Win 11

**Comment by lethargy123** [comment]
> 我也是，使用 rusb：：has_hotplug 方法会返回 false，这使得它在 Win 11 中无法使用

I tested my code on Windows 7 and Windows 10, and it worked fine in opening USB devices. However, it is not functioning properly on Windows 11. I agree with your observation that using the `rusb::has_hotplug` method will return false, rendering it unusable in Windows 11.

**Comment by a1ien** [comment]
This driver issues. Check if winusb driver is used for device. Also read this https://github.com/libusb/libusb/wiki/Windows#how-to-use-libusb-on-windows
