### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by h7x4** [a1ien/rusb#173]
Hello!

I've created a PR further downstream that depends on some features that have yet to be released. It seems like last release was March 26th, and a few commits has been made in between.

Would you mind creating a small version bump?

**Comment by a1ien** [comment]
I will but not early than next week.

**Comment by h7x4** [comment]
Great! Thank you

**Comment by h7x4** [comment]
Friendly ping :grin:

**Comment by a1ien** [comment]
Sorry. Yes make release on this week. The only thing stop me to doing it
need to prepare changelog. If you really want to make release faster you
can create PR with changelog :)

**Comment by h7x4** [comment]
I've added a new PR #178 with changelog and stuff.

I noticed that `Cargo.toml` still specifies `libusb1-sys.version = "0.6.0"` despite last release of this crate being `0.6.3`. Is there a reason behind this?

**Comment by a1ien** [comment]
I think we should update `libusb1-sys.version` to 0.6.3

**Comment by h7x4** [comment]
Turns out I was just confusing myself. It's ignoring the patch number already (i.e. `Cargo.lock` says `libusb1-sys` 0.6.4), but I've made a PR #179 to make it more obvious.
