### ISSUE TITLE
Question regarding linux gadget mode

### ISSUE THREAD

**Issue by robertosw** [a1ien/rusb#177]
I have a Raspberry Pi setup as a usb gadget, meaning in the usb connection it will act as the device, not as the host.
Using rusb::devices() on the device itself my "device" (/dev/hidg0)  is found and the vendor id is printed correctly.

Can this library be used to write HID Reports to this device? After reading the documentation briefly, I don't think so, but this crate is so well maintained that I kind of wish its possible :D

**Comment by kevinmehall** [comment]
No, the kernel APIs for gadget mode are different.

I wouldn't expect libusb / rusb to see a gadget-side interface at all. Are you sure the device you're seeing with rusb isn't a root hub? They use the same `1d6b` Linux Foundation VID that the gadget devices use by default.

**Comment by robertosw** [comment]
Yeah you're right. It doesnt matter which vendor id I create my device with. rusb always shows `1d6b`. Thank you :D
