### ISSUE TITLE
Trying to flash a chip, but getting "Can't init Global usb context, error Other"

### ISSUE THREAD

**Issue by daschawarde** [a1ien/rusb#188]
I am trying to flash my application to the chip (STM32) via Ubuntu, but it returns me "Can't init Global usb context, error Other":
thread 'main' panicked at /home/USER/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rusb-0.9.3/src/context.rs:217:28:
Can't init Global usb context, error Other

In Windows everything works fine, but with Ubuntu am I stuck.

**Comment by a1ien** [comment]
Maybe you try to do this inside docker? Actually this error came from [libusb](https://github.com/libusb/libusb).

**Comment by daschawarde** [comment]
Thank you for the advice! The issue was that one should manually attach USB in Ubuntu.
