### ISSUE TITLE
Next release on crates.io 

### ISSUE THREAD

**Issue by surban** [a1ien/rusb#198]
Could you publish a new version on crates.io?

This would be helpful for me, since I have crates that depend on rusb.

**Comment by a1ien** [comment]
I am currently on vacation. Nevertheless, I commit to delivering a new release by the second week of April.

**Comment by surban** [comment]
Sure, don't hurry. It was more of a heads-up that there is at least one dependent crate that would benefit from an updated release ;)

**Comment by a1ien** [comment]
Resolved #205
