### ISSUE TITLE
Compilation fails on i686-unknown-linux-gnu on GitHub runner because of missing bits/wordsize.h

### ISSUE THREAD

**Issue by ia0** [a1ien/rusb#211]
I'm not sure if it's `libusb1-sys` related, but I'm seeing a compilation error when compiling to i686-unknown-linux-gnu on an `ubuntu-latest` (22.04.5) GitHub runner. I can't reproduce it locally which makes it hard to fix. So I'm asking for advice in case you've seen this error in the past or would know how to fix it.

```
The following warnings were emitted during compilation:

warning: libusb1-sys@0.7.0: In file included from /usr/include/features.h:392,
warning: libusb1-sys@0.7.0:                  from /usr/include/assert.h:35,
warning: libusb1-sys@0.7.0:                  from libusb/libusb/libusbi.h:29,
warning: libusb1-sys@0.7.0:                  from libusb/libusb/os/linux_netlink.c:24:
warning: libusb1-sys@0.7.0: /usr/include/features-time64.h:20:10: fatal error: bits/wordsize.h: No such file or directory
warning: libusb1-sys@0.7.0:    20 | #include <bits/wordsize.h>
warning: libusb1-sys@0.7.0:       |          ^~~~~~~~~~~~~~~~~
warning: libusb1-sys@0.7.0: compilation terminated.

error: failed to run custom build command for `libusb1-sys v0.7.0`
```

Here's a failing workflow: https://github.com/google/wasefire/actions/runs/11052839944/job/30705877684?pr=617

**Comment by a1ien** [comment]
Hi, This looks like the issues with compiler toolchain. You need to bee ensure that you have installed gcc-multilib.
Because to be able to build 32bit application you need 32 library support.

**Comment by ia0** [comment]
Thanks a lot for the quick answer! That was it.
