### ISSUE TITLE
Unused "Success" Error variant

### ISSUE THREAD

**Issue by pheki** [a1ien/rusb#23]
Hey, first of all, thanks for this library!

In the [Error enum](https://docs.rs/rusb/0.5.5/rusb/enum.Error.html) the first variant is Success, which I believe should never be constructed as in all functions I've checked, you consider 0 as Ok(res).

I believe It would also be unidiomatic to return an Error::Success at any given time.

Would you consider removing that variant? It would be a breaking change, so we'd need to wait for 0.6 to include it.

I can create a Pull Request if you agree.

**Comment by a1ien** [comment]
>I believe It would also be unidiomatic to return an Error::Success at any given time.

Yes. I agree. We may remove Error::Success in 0.6.

I plane to make 0.6 version when libusb release v1.0.24
