### ISSUE TITLE
0.6 released but github code is still on 0.5

### ISSUE THREAD

**Issue by rukai** [a1ien/rusb#28]
Somehow 0.6 was published but github is still on 0.5.
Did you just forget to push it?

**Comment by a1ien** [comment]
Ohh... I only push to 0.6 tag. And forgot push to master.
I crate 0.6.1 version with metge last master and 0.6 tag

**Comment by rukai** [comment]
ok, thanks!
version in the readme is still out of date btw

**Comment by a1ien** [comment]
Fix
