### ISSUE TITLE
libusb can return 0 from bulk reads.

### ISSUE THREAD

**Issue by fletcherw** [a1ien/rusb#32]
In some of my testing using rusb, I ran into an issue where calls to io::Copy were ending earlier than expected.

I experimented, and apparently it is possible for a successful libusb_bulk_transfer to read 0 bytes.
Returning Ok(0) from bulk_read doesn't work well, because it suggests EOF. However, this is definitely not EOF.

What are your thoughts on returning rusb::Error::Interrupted in those cases as well?

**Comment by a1ien** [comment]
No. It's ZLP packet. It's ok. https://stackoverflow.com/questions/48975323/what-is-zero-length-packet
