### ISSUE TITLE
Incorrect `u8::MAX `?

### ISSUE THREAD

**Issue by flukejones** [a1ien/rusb#33]
```
[  164s]    Compiling rusb v0.6.2
[  164s] error[E0599]: no associated item named `MAX` found for type `u8` in the current scope
[  164s]   --> /home/abuild/rpmbuild/BUILD/asus-nb-ctrl-1.0.3/vendor/rusb/src/device_handle.rs:89:33
[  164s]    |
[  164s] 89 |         while self.index <= u8::MAX as u16 {
[  164s]    |                                 ^^^ associated item not found in `u8`
[  164s]    |
[  164s] help: you are looking for the module in `std`, not the primitive type
[  164s]    |
[  164s] 89 |         while self.index <= std::u8::MAX as u16 {
[  164s]    |                             ^^^^^^^^^^^^
[  164s] 
[  164s] error: aborting due to previous error
```

Unsure what is going on here. The last version I was using is 0.6.0, and I'm building for four distros in Open Build. I just updated to 6.0.2 and got the above error (and git blame indicates the related changes are 2 months old).

The distros that fail are fedora and ubuntu, while arch and opensuse are fine.
- Arch `rust-1:1.46.0-1`
- fedora `rust-1.42.0-1.fc32`
- opensuse `rust-1.44.1-3.1`
- ubuntu `rust-1.41-1`

Bit of a pain in the bum. The change is breaking, but only because of compiler changes. I've no idea how you would want to approach this..

**Comment by a1ien** [comment]
Hmm... seams need rust grater then 1.43 https://blog.rust-lang.org/2020/04/23/Rust-1.43.0.html#library-changes
For fix I can import `std::u8` but I recomend update compiler to latest version

**Comment by a1ien** [comment]
Also note. I recommend install rust compiler throught rustup and not use disto package

**Comment by flukejones** [comment]
Yeah I understand that. For my own projects I use rustup. But for distribution of a Linux daemon I need to use the provided tooling (in this case I use openbuild).

It's not really feasible for me to to get updates out to users any other way unfortunately. It looks like using `std::u8` wouldn't break anything, and this isn't `no-std` is it?

Linux is frustrating at times eh?

**Comment by a1ien** [comment]
Publish 0.6.3 version
