### ISSUE TITLE
Cannot create Device from file descriptor on Android

### ISSUE THREAD

**Issue by avantgardnerio** [a1ien/rusb#34]
Hello, and thank you for your fine library. Unfortunately, I'm trying to use it on Android, which is... less fine. When I run as root I can open USB Devices, but when I am running as a regular user / APK the only way to open them seems to be through the Android Java API. That API on the other-hand does expose the underlying file descriptor, and lib usb does provide [libusb_wrap_sys_device](http://libusb.sourceforge.net/api-1.0/group__libusb__dev.html#ga98f783e115ceff4eaf88a60e6439563c).

So, I was wondering if you would be open to a PR that either constructed a rusb device from a FD or from a raw `libusb_device`? I certainly understand there are arguments to be had on both sides. I'm just trying to figure out which way I should go with my project.

Thanks!

**Comment by a1ien** [comment]
I don't like ibusb_wrap_sys_device for two reasons
1) We must somehow check that FD not closed before we finish work
2) Work only in linux

You can try make `device::from_libusb` pub and check how it's work under android.

**Comment by avantgardnerio** [comment]
Thanks! I'll try it out and submit a PR if it works :)

**Comment by a1ien** [comment]
Closed by acc74ded0812b60addb82dcc6f6bd6c04151fb75
