### ISSUE TITLE
Unable to read USB device data on Windows

### ISSUE THREAD

**Issue by ProjectInitiative** [a1ien/rusb#35]
```Rust
fn print_device<T: UsbContext>(device_desc: &DeviceDescriptor, handle: &mut Option<UsbDevice<T>>)
{
    println!(
        "  iManufacturer        {:?}",
            handle.as_mut().map_or(String::new(), |h| h
            .handle
            .read_manufacturer_string(h.language, device_desc, h.timeout)
            .unwrap())
    );
    println!(
        "  iproduct        {:?}",
            handle.as_mut().map_or(String::new(), |h| h
            .handle
            .read_product_string_ascii(device_desc)
            .unwrap())
    );
}
```

![image](https://user-images.githubusercontent.com/6314611/92431319-d5888280-f15c-11ea-817e-80fa84b616fe.png)

Hello! I wrote this test function based on the example I found in the rusb repo. I have encountered this issue on Windows 10 1909. The manufacturer and product information do not seem to be accessible on Windows. I have tried running the application as a standard user and as administrator and received the same results as shown in the console output.

I have tested the same code in a Linux environment (Ubuntu 20.04 and Raspberry Pi OS) and properly printed the desired information. 

I tried using both `.read_product_string()` and `.read_product_string_ascii()` and achieved the same results (an empty string).

Thank you for your time and insight!

**Comment by a1ien** [comment]
Are you sure that `handle: &mut Option<UsbDevice<T>>` Some(UsbDevice)?
If yes check what `device_desc.manufacturer_string_index()` and `device_desc.product_string_index()` return

**Comment by ProjectInitiative** [comment]
Hello! I have added in more information, and cleaned up the test function:
```rust
fn print_device<T: UsbContext>(device_desc: &DeviceDescriptor, handle: &mut Option<UsbDevice<T>>)
{
    println!("{0:<20} {1:?}", 
            "iManufacturer",
            handle.as_mut().map_or(String::new(), |h| h
            .handle
            .read_manufacturer_string(h.language, device_desc, h.timeout)
            .unwrap())
    );
    println!("{0:<20} {1:?}",
            "iManufacturer index",
             device_desc.manufacturer_string_index().unwrap());
    println!(
            "{0:<20} {1:?}",
            "iProduct",
            handle.as_mut().map_or(String::new(), |h| h
            .handle
            .read_product_string_ascii(device_desc)
            .unwrap())
    );
    println!("{0:<20} {1:?}",
            "iProduct index", 
            device_desc.product_string_index().unwrap());
    
}
```

The first picture is in Windows, running as administrator:
![image](https://user-images.githubusercontent.com/6314611/92551253-2cf12600-f223-11ea-84cd-41189ac42c3d.png)

The next image is running the same function as root on Linux:
![image](https://user-images.githubusercontent.com/6314611/92551297-42fee680-f223-11ea-96fa-1dfe1e7a8b93.png)


Both have the same indices, however, the Windows version does not get the associated string.

**Comment by ProjectInitiative** [comment]
Note: I have tested this with wireless mice, wired mice, USB drives, and USB bluetooth modules.
The outcome is the same, Linux will get the string, but windows does not.

**Comment by a1ien** [comment]
Have you checked that handle have `Some(handle)` not `None`?
If you not install winusb driver for device you can't `open` device on windows
