### ISSUE TITLE
Need safe cloning of device handles for async support?

### ISSUE THREAD

**Issue by achan1989** [a1ien/rusb#52]
This is a question, not a definite problem.

When using async in C I think it's typical to open a device, then copy the device handle into multiple `libusb_fill_bulk_transfer()`.  This is safe if:

- You let all transfers finish before closing the device handle.
- You only close the device handle once.

Of course in C you have to keep track of this the hard way.

If we want safe async in Rust, I think we first need make `DeviceHandle` safe to copy.  And somehow prevent closing a device if any handles still exist.

Thoughts?

**Comment by kevinmehall** [comment]
How about using `Arc<DeviceHandle<T>>` for things that need to share DeviceHandle ownership?

**Comment by achan1989** [comment]
Oh, that's easier than I thought :P

It might need to be `Arc<RwLock<DeviceHandle<T>>>` -- even if you configure all the interfaces etc before sharing it, you might need to call `clear_halt()`, which is `&mut`.  That's a detail though.  I'll try it out.
