### ISSUE TITLE
pub use libusb1-sys?

### ISSUE THREAD

**Issue by ianrrees** [a1ien/rusb#56]
More of a question than an issue:  I'm using rusb for most USB access, and libusb1-sys to access the libusb asynchronous interface.  Since rusb depends on libusb1-sys, I wonder if it might be better if rusb exposed the libusb1-sys that it uses, rather than requiring projects that use both to depend on both libraries separately?

In particular, I wonder if there's some risk of the two libraries using subtly different versions of libusb and causing errors.

**Comment by a1ien** [comment]
I think it might make sense. Also I think about merging two repo `libusb1-sys` and `rusb` in one workspace.
If there are no objections, I plan to merge the repositories and re-export in the next minor release.

**Comment by ianrrees** [comment]
Sounds good to me, thanks!
