### ISSUE TITLE
`EndpointDescriptor` missing `bRefresh` and `bSynchAddress` fields

### ISSUE THREAD

**Issue by matallui** [a1ien/rusb#58]
Hi! Is there a way around the lack of `bRefresh` and `bSynchAddress` for the `EndpointDescriptor`?

I know `libusb1-sys` does provide all the fields but this crate doesn't provide an API to access those fields or even to know the length of the `EndpointDescriptor`, since it can be either `7` or `9` bytes long.

Any help would be appreciated. Thanks!

**Comment by a1ien** [comment]
Hi.

I will add access to these fields.

P.S. I plan merging `libusb1-sys` and `rusb` in one workspace. That allow easy maintenance  :wink:
Add after merge(week or two)

**Comment by matallui** [comment]
Thank you! That'll be great.

Meanwhile, is there any way around this? Is there anyway where I can maybe get to the `libusb1-sys` version of the descriptor and access those directly?

**Comment by a1ien** [comment]
You can get raw `libusb_device` from `rusb::Device` https://github.com/a1ien/rusb/blob/7af49627683bd477fa98d99c94f9e46f2380a3c9/src/device.rs#L58
And then call any function from `libusb1-sys` direct. Or patch `rusb` and add getter to `EndpointDescriptor<'a>`.

**Comment by matallui** [comment]
Awesome, thanks! I was looking into using the raw `libusb_device` but it seems like a lot of work for now. I will just patch `rusb` until you release the fix. Thanks for the help!
