### ISSUE TITLE
Hotplug callbacks are leaked when deregistering them

### ISSUE THREAD

**Issue by jonas-schievink** [a1ien/rusb#6]
See this TODO:

https://github.com/a1ien/rusb/blob/6c6f3ff0151d5692e473463fc7b62bc588ba71ee/src/context.rs#L133

**Comment by a1ien** [comment]
Yep. I know this problem. I think add some map for cleanup.
But I was hoping this PR https://github.com/libusb/libusb/pull/380 would be accepted. And we not need store them.
