### ISSUE TITLE
list which usb is android device

### ISSUE THREAD

**Issue by madaxemad** [a1ien/rusb#66]
hey 
how can just know how many android device is connected to usbs 
not using them just list how many android devices there
thanks so much

**Comment by a1ien** [comment]
what do you mean by 'android device'?
In general it's not possible.

**Comment by madaxemad** [comment]
thanks
if a android device connected and you take a log it recognize one usb is connected to android device mobile device
it's possible on libusb go
https://github.com/google/gousb
you can see company even on it example lsusb
hope find solution

**Comment by a1ien** [comment]
You maybe need this https://github.com/a1ien/rusb/blob/master/examples/list_devices.rs?

**Comment by a1ien** [comment]
Ah and also hgo example use this db http://www.linux-usb.org/usb.ids

**Comment by madaxemad** [comment]
yeap it's good solution but need really time to fix 
thanks a lot
