### ISSUE TITLE
Windows on ARM, Support.

### ISSUE THREAD

**Issue by sidd-kishan** [a1ien/rusb#68]
ARM64 build for the windows on arm driver and rusb binary will definitely speed up the USB-based peripheral driver development and make ease of access to learn to build drives on a windows-based platform for hobbyists, students, and engineers to adopt rust as a safe programming language for driver development.

Not only WOR but it will also help to extend driver support for surface devices and other arm-based windows devices like Qualcomm dev kit, Nvidia Tegra kits, and Windows Surface ARM devices.

Please let us know when can we have an ARM64 version for Windows on ARM OS. We can help you test We have Windows on Rasberry Pi setup. We at Windows on Rasberry Pi community will be glad to extend support in testing your drivers and tools for ARM64 builds for drivers and tools.

**Comment by a1ien** [comment]
I'm on vacation now, but when I return I'll try to add windows on arm

**Comment by sidd-kishan** [comment]
Dear @a1ien, Thanks for a prompt response, it will bring us closer to much-needed USB drivers to enable cheap and open windows-based cheap computing for learning and teaching software and devices interfacing.

Our Motivation:-

In countries like India, here education worthy notebooks can only be afforded by few people and at-most people can afford a television set as a digital appliance Windows on Rasberry Pi can serve as a great cheap platform for cheap computer devices, and having the support of this project will get us one step closer to building drivers for other peripherals like USB drawing pens. In this day and age of pandemic, many children in India are not able to attend education as lockdown is in effect and many families cannot afford to invest in the digital education of their children.

**Comment by a1ien** [comment]
Ok. Now I returned and can start work on this. But I need your help. Can you try setup https://github.com/microsoft/vcpkg and install libusb from vcpkg

**Comment by sidd-kishan** [comment]
Yes I am working on that I have windows on ARM on Qemu and installed on Rasberry pi 4B+ aswell

**Comment by sidd-kishan** [comment]
An Issue is being resolved [vcpkg issue 18718](https://github.com/microsoft/vcpkg/issues/18718)

**Comment by a1ien** [comment]
Can you try this examples on windows arm 
[examples.zip](https://github.com/a1ien/rusb/files/6758692/examples.zip)

**Comment by sidd-kishan** [comment]
We would need a libusb sys package as well till vcpkg is resolving their side.

**Comment by a1ien** [comment]
What you mean by "need a libusb sys package as well till vcpkg"

**Comment by a1ien** [comment]
Do you tried run examples on windows arm?
I ask because I just run ' ./vcpkg install libusb:arm64-windows` and `$env:VCPKGRS_DYNAMIC=1; cargo build --workspace -vv --examples --target aarch64-pc-windows-msvc`
And get this example. It's look like everything work

**Comment by a1ien** [comment]
I am close this issues since it's not rusb problem.
