### ISSUE TITLE
How do I get the file descriptors for use with event loops

### ISSUE THREAD

**Issue by detly** [a1ien/rusb#69]
I am trying to integrate `rusb` with the [Calloop event loop](https://github.com/Smithay/calloop/). Usually this involves getting file descriptors for polling and adding them to the loop. Anything that implements `AsRawFd` works.

In my case I'm mainly interested in hotplug events, so I want the "whole-context" file descriptors that are available from the [`get_pollfds()`](https://libusb.sourceforge.io/api-1.0/group__libusb__poll.html#ga54c27dcf8a95d2a3a03cfb7dd37eae63) call. Is there any (safe, preferably) way to get these?

**Comment by detly** [comment]
I achieved this through using rusb as a submodule and getting at `libusb1_sys` within my own project. Do you have a particular opinion about whether `libusb1_sys` and its types (eg. `libusb_pollfds`) should be exposed or not?

**Comment by a1ien** [comment]
You can add both `rusb` and `libusb1_sys` as dependency to you project and directly use any function from `libusb1_sys`
```
[dependencies]
rusb = "0.8.1"
libusb1-sys = "0.5.0"
```

```rust
    unsafe {
        libusb1_sys::libusb_get_pollfds(std::ptr::null_mut());
    }
```

You don't need to add `rusb` as submodule to achieve this.

**Comment by detly** [comment]
Won't this pull `libusb1_sys` from `crates.io`, which is based on the deprecated standalone repository?

**Comment by a1ien** [comment]
Yes? but it's must not be a problem.
P.S. As I say in #56 i add re-export for `libusb1-sys`. I think do this in couple of week and releasing major version with #72 and #71

**Comment by detly** [comment]
Great, thanks!
