### ISSUE TITLE
Support Serde

### ISSUE THREAD

**Issue by raphaelcohn** [a1ien/rusb#81]
I've just started using rusb for a project involving a replacement for PC/SC, and I've found it very good - much better than many c-library wrappers.

One thing that is missing is optional support for serde for some of the provided types, eg `Version`. I'm currently dumping out captured properties to debug an issue, and it'd be nice to have serde support for these, rather than having to write wrappers or the like.

Should be trivial to add. Please?

**Comment by a1ien** [comment]
What type you want to add serde derive?
If it's only `Version` and some other type, that I think better use https://serde.rs/remote-derive.html

**Comment by raphaelcohn** [comment]
That solution requires me to create a new type wrapper for Version to eliminate duplication... at which point I may as well just create my own type.

**Comment by a1ien** [comment]
I close this since it's not issues. If someone wants to add support `serde` I am welcome for PR. Or please describe full list of struct which one you wand (de)serialize
