### ISSUE TITLE
Change TransferType

### ISSUE THREAD

**Issue by raphaelcohn** [a1ien/rusb#84]
TransferType should be defined as:-

```
#[derive(Debug, Clone, Ord, PartialOrd, Eq, PartialEq, Hash)]
pub enum UsbTransferType
{
	/// Control endpoint.
	Control,
	
	/// Isochronous endpoint.
	Isochronous
	{
		sync_type: UsbIschronousTransferSynchronizationType,
		
		usage_type: UsbIschronousTransferUsageType,
	},
	
	/// Bulk endpoint.
	Bulk,
	
	/// Interrupt endpoint.
	Interrupt,
}
```

This would be a breaking change, but it better reflects the USB specification.

**Comment by a1ien** [comment]
Sounds reasonable. I will try to implement this.

**Comment by raphaelcohn** [comment]
I've got a revised view:-

```
/// USB end point transfer type.
#[derive(Debug, Clone, Ord, PartialOrd, Eq, PartialEq, Hash)]
#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub enum UsbTransferType
{
	/// Control endpoint.
	Control,
	
	/// Isochronous endpoint.
	Isochronous
	{
		/// Direction.
		direction: UsbDirection,
		
		/// Synchronization type.
		synchronization_type: UsbIschronousTransferSynchronizationType,
		
		/// Usage type.
		usage_type: UsbIschronousTransferUsageType,
		
		additional_transaction_opportunities_per_microframe: AdditionalTransactionOpportunitiesPerMicroframe,
	},
	
	/// Bulk endpoint.
	Bulk
	{
		/// Direction.
		direction: UsbDirection
	},
	
	/// Interrupt endpoint.
	Interrupt
	{
		/// Direction.
		direction: UsbDirection,
		
		additional_transaction_opportunities_per_microframe: AdditionalTransactionOpportunitiesPerMicroframe,
	},
}

#[derive(Debug, Copy, Clone, Ord, PartialOrd, Eq, PartialEq, Hash)]
#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
#[repr(u8)]
pub enum AdditionalTransactionOpportunitiesPerMicroframe
{
	/// Zero.
	Zero = 0b00,
	
	/// One.
	One = 0b01,
	
	/// Two.
	Two = 0b10,
	
	/// Reserved.
	Reserved = 0b11,
}

```

**Comment by a1ien** [comment]
This naming `additional_transaction_opportunities_per_microframe` was crap. Why you not name like this

usb_bus_hardware_additional_transaction_opportunities_per_microframe_for_this_endpoint

P.S. I don't understand what this variable and how we get them from libusb.

**Comment by raphaelcohn** [comment]
I'd appreciate it you could elevate your conversation beyond 'crap' with something a little more articulate with some explanatory power.

Regardless, I've decided to eliminate the use of Rusb from my project. I appreciate your hard work; I just want to model my problems more accurately, with handling of edge cases appropriate to my needs and a lower performance overhead (eg your bit set implementation for claimed interfaces, the creation of a vector then chunking it before passing to `String::from_utf16` when a simple transmute of the array is provably correct . I'll continue to use the underlying C library binding you've worked on for now.

**Comment by a1ien** [comment]
Sorкy for "crap" I was just in a bad mood. Maybe for you project libusb1-sys better.

>your bit set implementation for claimed interfaces, the creation of a vector then chunking it before passing to String::from_utf16 when a simple transmute of the array is provably correct . 

No it's incorrect because to many device which pass incorrect strings and not follow usb specifications. And this can lead to unsound

**Comment by raphaelcohn** [comment]
Yes, many USB devices violate specifications; but it is not unsound - and it is provably so:-

Given a string descriptor byte buffer returned with contents from something that gets a descriptor:-

- Validate the buffer length does not exceed 255 bytes (pass a [u8; 255] in the first place).
- Validate the result is positive or zero;
- Validate the result is >= 2.
- Validate the bLength
- Validate the bDescriptorType
- Reject any buffer with a result % 2 != 0 (no need for & 0x01 - the compiler optimizes this for you).
- One now has a buffer with a multiple of 2 bytes eg &[u8]
- Simply transmute to &[u16] - not unsound
- Pass saif &[u16] to String::from_u16, or, if you're like me and (a) find the String implementation slow and (b) want to control allocation (eg to check for out of memory) write your own from utf16 le implementation that handles unbalanced surrogate pairs.
- Done.

Or your way:-
Create a new Vec, copy the bytes to it, chunk it, then create a Second Vec inside String using String::from_u16, then convert all errors to BadDescriptor and hide any causes of failure.

**Comment by a1ien** [comment]
>Simply transmute to &[u16] - not unsound

You forgot about alignment.

>Pass saif &[u16] to String::from_u16, or, if you're like me and (a) find the String implementation slow and (b) want to control allocation (eg to check for out of memory) write your own from utf16 le implementation that handles unbalanced surrogate pairs.

You still need dynamic allocation for string.

I can agree that we can remove one allocation but it's must implement correct. And allocate only one in String.

**Comment by a1ien** [comment]
We can do some think like this.

```rust
let mut buf = [0u16; 128];

let len = {
    let buf = unsafe { std::slice::from_raw_parts_mut(buf.as_mut_ptr().cast::<u8>(), 256) };

    let len = self.read_control(
        request_type(Direction::In, RequestType::Standard, Recipient::Device),
        LIBUSB_REQUEST_GET_DESCRIPTOR,
        u16::from(LIBUSB_DT_STRING) << 8 | u16::from(index),
        language.lang_id(),
        buf,
        timeout,
    )?;
    if len < 2 || buf[0] != len as u8 || len & 0x01 != 0 {
        return Err(Error::BadDescriptor);
    }
    len
};

if len == 2 {
    return Ok(String::new());
}

// len in bytes
String::from_utf16(&buf[..(len / 2)]).map_err(|_| Error::Other)
```

**Comment by raphaelcohn** [comment]
`[0u16; 128];` - maybe use a MaybeUninit (sic).

As for alignment, it doesn't in practice matter on the platforms I usually use... but I take your point.

**Comment by raphaelcohn** [comment]
For interest:-

```
line(always)]
	fn get_localized_string(&self, string_descriptor_index: NonZeroU8, (language_identifier, language): (LanguageIdentifier, Language)) -> Result<DeadOrAlive<String>, GetLocalizedStringError>
	{
		use ControlTransferError::*;
		use DeadOrAlive::*;
		use GetLocalizedStringError::*;
		use GetStandardUsbDescriptorError::GetDescriptor;
		
		let mut buffer = MaybeUninit::uninit_array();
		let remaining_bytes = match get_string_device_descriptor_language(self.device_handle.as_non_null(), &mut buffer, string_descriptor_index, language_identifier)?
		{
			Dead => return Ok(Dead),
			
			Alive(None) => return Err(StringIndexNonZeroButDeviceDoesNotSupportGettingString { string_descriptor_index, language }),
			
			Alive(Some(remaining_bytes)) => remaining_bytes,
		};
		
		let array_length_in_bytes = remaining_bytes.len();
		const ArrayElementSize: usize = 2;
		if unlikely!(array_length_in_bytes % ArrayElementSize != 0)
		{
			return Err(NotACorrectUtf16LittleEndianSize)
		}
		
		let array_length_in_u16 = array_length_in_bytes / ArrayElementSize;
		
		// Surrogate pairs encode from 2 x u16 to 4 x bytes; no change.
		// UTF-16 LE 0xFFFF encodes to three bytes; 1.5x growth.
		let maximum_number_of_utf_8_bytes = array_length_in_bytes * 3;
		let mut utf_8_bytes = Vec::new_with_capacity(maximum_number_of_utf_8_bytes).map_err(CouldNotAllocateString)?;
		
		let array = unsafe { from_raw_parts(remaining_bytes.as_ptr() as *const u16, array_length_in_u16) };
		for result in decode_utf16(array.iter().cloned())
		{
			let character = result.map_err(InvalidUtf16LittleEndianSequence)?;
			Self::encode_utf8_raw(character, &mut utf_8_bytes);
		}
		
		Ok(Alive(unsafe { String::from_utf8_unchecked(utf_8_bytes) }))
	}
	
	#[inline(always)]
	fn encode_utf8_raw(character: char, utf_8_bytes: &mut Vec<u8>)
	{
		const TAG_CONT: u8 = 0b1000_0000;
		const TAG_TWO_B: u8 = 0b1100_0000;
		const TAG_THREE_B: u8 = 0b1110_0000;
		const TAG_FOUR_B: u8 = 0b1111_0000;
		
		let code = character as u32;
		if likely!(code < 0x80)
		{
			utf_8_bytes.push(code as u8)
		}
		else if likely!(code < 0x800)
		{
			utf_8_bytes.push((code >> 6 & 0x1F) as u8 | TAG_TWO_B);
			utf_8_bytes.push((code & 0x3F) as u8 | TAG_CONT)
		}
		else if likely!(code < 0x10000)
		{
			utf_8_bytes.push((code >> 12 & 0x0F) as u8 | TAG_THREE_B);
			utf_8_bytes.push((code >> 6 & 0x3F) as u8 | TAG_CONT);
			utf_8_bytes.push((code & 0x3F) as u8 | TAG_CONT);
		}
		else
		{
			utf_8_bytes.push((code >> 18 & 0x07) as u8 | TAG_FOUR_B);
			utf_8_bytes.push((code >> 12 & 0x3F) as u8 | TAG_CONT);
			utf_8_bytes.push((code >> 6 & 0x3F) as u8 | TAG_CONT);
			utf_8_bytes.push((code & 0x3F) as u8 | TAG_CONT);
		}
	}
```
