### ISSUE TITLE
Document the endianness of the u16 passed to Version::from_bcd

### ISSUE THREAD

**Issue by raphaelcohn** [a1ien/rusb#87]
Document the endianness of the u16 passed to Version::from_bcd. Whilst I presume this is LE, it would be nice to make it clear.

**Comment by a1ien** [comment]
PR with improved documentation is always welcome

**Comment by a1ien** [comment]
And what you men by endian? it's hex value. Value don have endianness In doc all clear explain.

>    /// Extracts a version from a binary coded decimal (BCD) field. BCD fields exist in USB
    /// descriptors as 16-bit integers encoding a version as `0xJJMN`, where `JJ` is the major
    /// version, `M` is the minor version, and `N` is the sub minor version. For example, 2.0 is
    /// endoded as `0x0200` and 1.1 is encoded as `0x0110`.

P.S. Ned fix typo
