### ISSUE TITLE
How to create a language

### ISSUE THREAD

**Issue by Animeshz** [a1ien/rusb#93]
Is there no public API to make an instance of Language? I couldn't find a way to make Language either from a raw hex or from using PrimaryLanguage and SecondaryLanguage.

https://github.com/a1ien/rusb/blob/f611e84804723c73c6b6993c73b5bfa2c44ab025/src/language.rs#L11-L39

**Comment by a1ien** [comment]
For what purpose you need make an instance of `Language`?

**Comment by Animeshz** [comment]
@a1ien Reading a string descriptor from particular usb device, `DeviceHandle::read_string_descriptor` particularly.

**Comment by a1ien** [comment]
You can get Language from `DeviceHandle::read_languages`.

**Comment by Animeshz** [comment]
Oh thanks 👀
